Runner:
  Name: FileSystemWatchingRunner
  Parameters: 
     FolderToWatch: f:\SomeFolderToMonitorForChanges
     VerboseOutput: true
Plugins:
- Name: MSBuild
Notifications:
- Name: ConsoleNotification
- Name: GrowlNotification