RunnerConfiguration:
  Name: FileSystemWatchingRunner
PluginsConfiguration:
- Name: MSBuild
  DependentPlugins:
  - Name: FileCopy
    Parameters: F:\research\Watching\src\SAHL.Core\SAHL.Core\bin\Debug->F:\research\Watching\src\SAHL.Core.Console\SAHL.Core.Console\bin\Debug
NotificationsConfiguration:
- Name: ConsoleNotification
- Name: GrowlNotification