RunnerConfiguration:
  Name: FileSystemWatchingRunner
PluginsConfiguration:
- Name: MSBuild
  DependentPlugins:
  - Name: FileCopy
    Parameters: C:\SomeFolder->F:\AnotherFolder
NotificationsConfiguration:
- Name: ConsoleNotification
- Name: GrowlNotification