RunnerConfiguration:
  Name: FileSystemWatchingRunner
PluginsConfiguration:
- Name: MSBuild
  DependentPlugins:
  - Name: FileCopy
    Parameters:
      From: SomeFolder
      To: AnotherFolder
NotificationsConfiguration:
- Name: ConsoleNotification
- Name: GrowlNotification